<?php

class CheckPackage extends CApplicationComponent
{

    public function __construct()
    {

        parent::init(); // TODO: Change the autogenerated stub
    }

    public static function Validate($users,$total) {
        $server_name = str_replace('www.', '', $_SERVER['SERVER_NAME']);
        if($server_name!=Yii::app()->params['main_domain']) {
            if (isset($GLOBALS['package'][$users]) and $total < $GLOBALS['package'][$users] )
                return true;
            else
                return false;
        }
        else {
            return  true;
        }
    }

    public static function CheckPackage(){

        $server_name = str_replace('www.', '', $_SERVER['SERVER_NAME']);
        if($server_name!=Yii::app()->params['main_domain']) {
            if (isset($GLOBALS['package']['id']) > 2)
                return true;
            else
                return false;
        }
        else{
            return  true;
        }
    }

    public static function getSpace(){
        $server_name = str_replace('www.', '', $_SERVER['SERVER_NAME']);
        if($server_name!=Yii::app()->params['main_domain']) {
            $total = $GLOBALS['package']['diskspace'];
            $dir = "/images/domains/";
            return (getSizeUsed($dir) / $total) * 100;
        }
        else{
            return '';
        }
    }

    private function getSizeUsed($dir) {
        $size = 0;
        foreach (glob(rtrim($dir, '/').'/*', GLOB_NOSORT) as $each)
            $size += is_file($each) ? filesize($each) : getSizeUsed($each);
        return $size;
    }
}